sudo: required

services:
  - docker

before_install:
  - docker run --detach --publish 5432:5432 --name postgres kiasaki/alpine-postgres
  - sleep 10

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
